# [[file:~/Workspace/Programming/gchemol/gchemol.note::c45d1413-12b8-471e-b060-da682339ad4b][c45d1413-12b8-471e-b060-da682339ad4b]]
[package]
name = "gchemol"
version = "0.0.19"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[workspace]
members = ["geometry",]

[dependencies]
nalgebra = "0.16.0"
nom = ">=4.0.0"
petgraph = "*"
indexmap = {version=">=1.0.0", features=["serde-1"]}
serde = "*"
serde_json = "*"
serde_derive = "1.0"
handlebars = ">=1.0.0"
itertools = "*"
quicli = "0.3"
gchemol-geometry = {path = "geometry"}

[dev-dependencies]
approx = "0.3"
tempfile = "3"
# c45d1413-12b8-471e-b060-da682339ad4b ends here
