# [[file:~/Workspace/Programming/gchemol/gchemol.note::c45d1413-12b8-471e-b060-da682339ad4b][c45d1413-12b8-471e-b060-da682339ad4b]]
[package]
name = "gchemol"
version = "0.0.1"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
approx = "*"
cgmath = "*"
timeit = "*"
itertools = "*"
rand = ">=0.5.0-pre.0"
# c45d1413-12b8-471e-b060-da682339ad4b ends here
