# [[file:~/Workspace/Programming/gchemol/gchemol.note::c45d1413-12b8-471e-b060-da682339ad4b][c45d1413-12b8-471e-b060-da682339ad4b]]
[package]
name = "gchemol"
version = "0.0.16"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
approx = "*"
nalgebra = ">=0.14.4"
#cgmath = "*"
nom = ">=4.0.0"
petgraph = "*"
indexmap = {version=">=1.0.0", features=["serde-1"]}
serde = "*"
serde_json = "*"
serde_derive = "1.0"
handlebars = "0.32.3"
itertools = "*"
quicli = "*"
rand = ">=0.5"
# c45d1413-12b8-471e-b060-da682339ad4b ends here
