# cargo

# [[file:~/Workspace/Programming/gchemol/core/gchemol-core.note::*cargo][cargo:1]]
[package]
name = "gchemol-core"
version = "0.0.22"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
nalgebra = "0.16.0"
petgraph = "0.4.13"
indexmap = {version=">=1.0.0", features=["serde-1"]}
serde = "*"
serde_json = "*"
serde_derive = "1.0"
itertools = "*"
quicli = "0.3"
gchemol-geometry = {path = "../geometry"}

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
