# cargo

# [[file:~/Workspace/Programming/gchemol/core/gchemol-core.note::*cargo][cargo:1]]
[package]
name = "gchemol-core"
version = "0.0.23"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
nalgebra = "*"
petgraph = "*"
indexmap = {version=">=1.0.0", features=["serde-1"]}
serde = "*"
serde_json = "*"
serde_derive = "*"
itertools = "*"
quicli = "*"
gchemol-geometry = {path = "../geometry"}

[dev-dependencies]
approx = "*"
# cargo:1 ends here
