# [[file:~/Workspace/Programming/gchemol/readwrite/readwrite.note::86fc103f-aa7d-42fb-9c7f-fb5acbf8cfd3][86fc103f-aa7d-42fb-9c7f-fb5acbf8cfd3]]
[package]
name = "gchemol-readwrite"
version = "0.0.19"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
nom = ">=4.0.0"
handlebars = ">=1.0.0"
quicli = "0.3"
indexmap = "1.0"
itertools = "0.7"
gchemol-core = {path = "../core"}
serde = "*"
serde_json = "*"
serde_derive = "1.0"

[dev-dependencies]
approx = "0.3"
tempfile = "3"
# 86fc103f-aa7d-42fb-9c7f-fb5acbf8cfd3 ends here
